// Short, source-grounded labels used to make each guide scannable at a glance.
// `flow` reads left to right; `compare` presents related options side by side.
export const guideVisuals = {
  'getting-started': { kind: 'flow', items: ['Open Soonshot', 'Review permissions', 'Start exploring'] },
  'sign-in': { kind: 'flow', items: ['Choose a social sign-in', 'Use the same method next time'] },
  home: { kind: 'compare', items: ['Featured stories', 'Trending titles', 'Continue Watching'] },
  explore: { kind: 'flow', items: ['Your region', 'Available stories'] },
  previews: { kind: 'flow', items: ['Browse previews', 'Open a story'] },
  'episode-page': { kind: 'flow', items: ['Story details', 'Episode list', 'Continue Watching'] },
  events: { kind: 'compare', items: ['Event video', 'Linked experience'] },
  profile: { kind: 'flow', items: ['Your profile', 'Available name'] },
  'watch-history': { kind: 'flow', items: ['Started story', 'Continue Watching'] },
  'saved-stories': { kind: 'flow', items: ['Save a story', 'Find it in your list'] },
  'gift-codes': { kind: 'flow', items: ['Profile menu', 'Gift Code', 'Register', 'Stickers added'] },
  stickers: { kind: 'flow', items: ['Free Stickers first', 'Paid Stickers next', 'Unlock an episode'] },
  announcements: { kind: 'flow', items: ['App menu', 'Announcements'] },
  settings: { kind: 'flow', items: ['Profile menu', 'Settings'] },
  notifications: { kind: 'compare', items: ['App permission', 'Device settings'] },
  'episode-details': { kind: 'flow', items: ['Teaser', 'Episode 1', 'Episode 2…'] },
  'purchase-messages': { kind: 'compare', items: ['Amount', 'Renewal period', 'Terms'] },
  'free-episodes': { kind: 'flow', items: ['Open a story', 'Find the Free label', 'Watch'] },
  'featured-banner': { kind: 'compare', items: ['New releases', 'Stories viewers enjoy'] },
  surveys: { kind: 'flow', items: ['Invitation', 'Answer survey', 'Completed'] },
  'survey-results': { kind: 'flow', items: ['Responses', 'Review', 'Summary'] },
  'ai-chat': { kind: 'flow', items: ['5 free messages', 'Check the cost', '1 Sticker per message'] },
  'unlock-episodes': { kind: 'flow', items: ['Choose an episode', 'Review Sticker cost', 'Unlock'] },
  fanpass: { kind: 'flow', items: ['Get a rental pass', 'Choose an eligible story', 'Watch during your plan'] },
  membership: { kind: 'compare', items: ['$9.99 / month', 'Eligible episodes', 'Review checkout'] },
  'share-stories': { kind: 'flow', items: ['Story poster', 'Share, if available'] },
  'earn-rewards': { kind: 'compare', items: ['Daily check-in', 'Rewarded ads', 'One-time tasks'] },
  'sticker-expiration': { kind: 'compare', items: ['Rewards · 7 days', 'Pack bonus · 30 days', 'Paid · no expiry'] },
  'recommendation-popups': { kind: 'flow', items: ['Watch a story', 'Survey or suggestion'] },
  'contact-support': { kind: 'flow', items: ['Send inquiry', 'Acknowledgment', 'Team reply'] },
  refunds: { kind: 'flow', items: ['Store confirms refund', 'Benefit adjusts', 'History updates'] },
  promotions: { kind: 'flow', items: ['Eligible offer', 'Review checkout'] },
  'app-updates': { kind: 'flow', items: ['Open app store', 'Update Soonshot'] },
  'prices-and-rewards': { kind: 'compare', items: ['Stickers from $4.49', 'FanPass $1.99 / month', 'Membership $9.99 / month'] },
  'delete-account': { kind: 'flow', items: ['Close account', '30-day cooldown', 'Register again'] },
}
